### ISSUE TITLE
(Lua 5.3) lua_tounsigned available with LUA_COMPAT_5_2 definition only.

### ISSUE THREAD

**Issue by yisonPylkita** [jeremyong/Selene#74] opened 2015-06-25 13:45 UTC
In Lua 5.3 `lua_tounsigned` (and others `unsigned`) has been marked as deprecated.
They are available with `LUA_COMPAT_5_2` compiler definition.

After adding 
```cmake
add_definitions(-DLUA_COMPAT_5_2)
```
to the `CMakeLists.txt` tests compile, but one test failed: 
- `test_call_undefined_function2`

`Arch Linux 4.0.6-1
gcc 5.1.0-4
cmake 3.2.3-1
lua 5.3.1-1`

**Comment by jeremyong** [comment] 2015-06-25 15:02
Do you have any failure output?

**Comment by yisonPylkita** [comment] 2015-06-25 15:33
Compilation output without `LUA_COMPAT_5_2` flag

```
[100%] Building CXX object CMakeFiles/test_runner.dir/test/Test.cpp.o
In file included from /home/arlen/Selene/include/selene/function.h:6:0,
                 from /home/arlen/Selene/include/selene/exotics.h:3,
                 from /home/arlen/Selene/include/selene/BaseFun.h:3,
                 from /home/arlen/Selene/include/selene/ClassFun.h:3,
                 from /home/arlen/Selene/include/selene/Class.h:3,
                 from /home/arlen/Selene/include/selene/Registry.h:3,
                 from /home/arlen/Selene/include/selene/State.h:6,
                 from /home/arlen/Selene/include/selene.h:3,
                 from /home/arlen/Selene/test/class_tests.h:3,
                 from /home/arlen/Selene/test/Test.cpp:2:
/home/arlen/Selene/include/selene/primitives.h: In function 'unsigned int sel::detail::_get(sel::detail::_id<unsigned int>, lua_State*, int)':
/home/arlen/Selene/include/selene/primitives.h:62:35: error: 'lua_tounsigned' was not declared in this scope
     return lua_tounsigned(l, index);
                                   ^
/home/arlen/Selene/include/selene/primitives.h: In function 'int sel::detail::_check_get(sel::detail::_id<int>, lua_State*, int)':
/home/arlen/Selene/include/selene/primitives.h:97:34: error: 'luaL_checkint' was not declared in this scope
     return luaL_checkint(l, index);
                                  ^
/home/arlen/Selene/include/selene/primitives.h: In function 'unsigned int sel::detail::_check_get(sel::detail::_id<unsigned int>, lua_State*, int)':
/home/arlen/Selene/include/selene/primitives.h:102:39: error: 'luaL_checkunsigned' was not declared in this scope
     return luaL_checkunsigned(l, index);
                                       ^
/home/arlen/Selene/include/selene/primitives.h: In function 'void sel::detail::_push(lua_State*, sel::MetatableRegistry&, unsigned int)':
/home/arlen/Selene/include/selene/primitives.h:250:26: error: 'lua_pushunsigned' was not declared in this scope
     lua_pushunsigned(l, u);
                          ^
/home/arlen/Selene/include/selene/primitives.h: In function 'void sel::detail::_push(lua_State*, unsigned int)':
/home/arlen/Selene/include/selene/primitives.h:293:26: error: 'lua_pushunsigned' was not declared in this scope
     lua_pushunsigned(l, u);
                          ^
CMakeFiles/test_runner.dir/build.make:54: recipe for target 'CMakeFiles/test_runner.dir/test/Test.cpp.o' failed
make[2]: *** [CMakeFiles/test_runner.dir/test/Test.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/test_runner.dir/all' failed
make[1]: *** [CMakeFiles/test_runner.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

Test output
```
Executing 71 tests...
...x...................................................................
70 out of 71 tests finished successfully.

Test "test_call_undefined_function2" failed.

```

**Comment by yisonPylkita** [comment] 2015-06-25 15:58
Forget about unit test error. I have compiled Selene (`Test.cpp`) with `Lua 5.2` and there is still this error, so I think there is no relation beetwen them.

But there is still problem with Lua 5.3. Will you re-write (part of) Selene or stay in compatibile (`Lua 5.2`) mode ?

**Comment by jeremyong** [comment] 2015-06-25 17:54
I will probably provide a build time preprocessor define that lets you choose the Lua version and make Selene compatible with both.

I'm curious about the undefined function fail.

**Comment by gczuczy** [comment] 2015-07-20 09:52
I've opened https://github.com/jeremyong/Selene/issues/76 which is actually a duplicate of this.Sorry for the lack is proper prior googling.

**Closed** 2015-08-20 00:18 UTC
